import { readFile } from "node:fs/promises";
import path from "node:path";
import { cache } from "react";

import type { EvidenceBundle, EvidenceResult } from "./types";

/**
 * THE ONLY PLACE THIS APP READS DATA.
 *
 * Today the bundle is a static export of a finished run, sitting in
 * `public/evidence.json` (git-ignored — it is real customer-adjacent data).
 * Tomorrow it is a poll against the Python API in `api/`, which already serves
 * `GET /api/approvals/<id>` and friends but has no database yet.
 *
 * That switch is meant to be this file and nothing else, so:
 *  - every page calls `getEvidence()` and nothing else;
 *  - the return type is a RESULT, not a bundle, because a live fetch fails and
 *    the pages have to already know how to render "we could not read it";
 *  - the function is async even though a file read could be sync, so a network
 *    implementation drops in without touching a single call site;
 *  - nothing downstream imports `node:fs`.
 *
 * `cache()` dedupes the read across the component tree within one request.
 *
 * This module is server-only by construction (it imports `node:fs`) and is
 * imported exclusively by server components; no client component may import it.
 */

const BUNDLE_FILE = "evidence.json";

function bundlePath(): string {
  return path.join(process.cwd(), "public", BUNDLE_FILE);
}

/**
 * Structural check before anything is handed to the UI. A truncated or
 * half-written file must surface as a read failure, not as a page that renders
 * zero runs and zero problems.
 */
function looksLikeBundle(value: unknown): value is EvidenceBundle {
  if (typeof value !== "object" || value === null) return false;
  const b = value as Partial<EvidenceBundle>;
  return (
    typeof b.schema === "string" &&
    Array.isArray(b.runs) &&
    typeof b.headline === "object" &&
    b.headline !== null &&
    typeof b.log_integrity === "object" &&
    b.log_integrity !== null
  );
}

export const getEvidence = cache(async function getEvidence(): Promise<EvidenceResult> {
  const source = `public/${BUNDLE_FILE}`;
  let raw: string;
  try {
    raw = await readFile(bundlePath(), "utf8");
  } catch {
    return {
      ok: false,
      source,
      reason:
        `No evidence bundle is present at ${source}. It is generated by ` +
        "`python -m ctrl_a_jr.export --out web/evidence.json` and copied in at " +
        "build time; it is never committed, because it is derived from a real " +
        "activity log.",
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { ok: false, source, reason: `${source} is present but is not valid JSON.` };
  }

  if (!looksLikeBundle(parsed)) {
    return {
      ok: false,
      source,
      reason: `${source} parsed, but is not a ctrl-a-jr evidence bundle (missing schema, runs, headline or log_integrity).`,
    };
  }

  return { ok: true, source, bundle: stripPrerenderedHtml(parsed) };
});

/**
 * Drop `artifact_html` at the boundary.
 *
 * The exporter ships a pre-rendered HTML card per tool call. It is honest
 * markup — artifacts.py escapes every value — but rendering a string as HTML
 * would mean this app has a code path that turns run-derived text into DOM, and
 * the fields in those cards quote a customer's own email. Cutting the string
 * out here means the property is structural: there is nothing in the tree for
 * `dangerouslySetInnerHTML` to be pointed at, by me or by the next person.
 *
 * The cards are rebuilt in React from the structured fields instead — see
 * components/channel-frames.tsx, which ports artifacts.py's typed-renderer
 * idea rather than its output.
 */
function stripPrerenderedHtml(bundle: EvidenceBundle): EvidenceBundle {
  return {
    ...bundle,
    runs: bundle.runs.map((run) => ({
      ...run,
      events: run.events.map(({ artifact_html: _html, ...e }) => e),
      approvals: run.approvals.map(({ artifact_html: _html, ...a }) => a),
    })),
  };
}

/**
 * Resolve the run the URL asked for. An unknown id falls back to the most
 * recent run and SAYS SO through `matched`, rather than silently showing a
 * different run than the link promised.
 */
export function selectRun(bundle: EvidenceBundle, requested?: string) {
  const runs = bundle.runs;
  if (runs.length === 0) return { run: null, matched: false as const };
  if (!requested) return { run: runs[runs.length - 1], matched: true as const };
  const hit = runs.find((r) => r.run_id === requested);
  return hit
    ? { run: hit, matched: true as const }
    : { run: runs[runs.length - 1], matched: false as const };
}
